name: kde-frameworks-5
version: 5.26
summary: KDE Frameworks 5
description: KDE Frameworks are addons and useful extensions to Qt
confinement: devmode
grade: devel

slots:
    kde-frameworks-5-slot:
        content: kde-frameworks-5-all
        interface: content
        read: [usr]

parts:
    qt5:
        plugin: nil
        build-packages:
            - qtbase5-dev
            - qtscript5-dev
            - qtdeclarative5-dev
            - qttools5-dev
            - qttools5-dev-tools
        stage-packages:
            - libqt5concurrent5
            - libqt5core5a
            - libqt5dbus5
            - libqt5gui5
            - libqt5network5
            - libqt5printsupport5
            - libqt5sql5
            - libqt5test5
            - libqt5widgets5
            - libqt5xml5
            - qtchooser
        filesets:
            exclusion:
                - -etc # All in core
                - -var # All in core
                - -lib # All in core
                - -usr/lib/*/cmake/*
                - -usr/include
                - -usr/share/doc/*
                - -usr/share/man/*
                - -usr/lib/gcc
                - -usr/lib/*.a
                - -usr/lib/*/*.a
                - -usr/lib/*/*.prl
                - -usr/lib/*/pkgconfig/*
        snap: [$exclusion]
    extra-cmake-modules:
        after: [qt5]
        plugin: cmake
        source: http://download.kde.org/stable/frameworks/5.26/extra-cmake-modules-5.26.0.tar.xz
        configflags:
            - -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
            - -DCMAKE_INSTALL_PREFIX=/usr
            - -DCMAKE_BUILD_TYPE=Debug
        filesets:
            exclusion:
                - -usr/lib/*/cmake/*
                - -usr/include/*
                - -usr/share/ECM/*
                - -usr/share/doc/*
                - -usr/share/man/*
        snap: [$exclusion]
    ki18n:
        after: [extra-cmake-modules]
        plugin: cmake
        source: http://download.kde.org/stable/frameworks/5.26/ki18n-5.26.0.tar.xz
        configflags:
            - -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
            - -DCMAKE_INSTALL_PREFIX=/usr
            - -DCMAKE_BUILD_TYPE=Debug
        stage-packages: []
        filesets:
            exclusion:
                - -usr/lib/*/cmake/*
                - -usr/include/*
                - -usr/share/ECM/*
                - -usr/share/doc/*
                - -usr/share/man/*
        snap: [$exclusion]
    kcoreaddons:
        after: [extra-cmake-modules, ki18n]
        plugin: cmake
        source: http://download.kde.org/stable/frameworks/5.26/kcoreaddons-5.26.0.tar.xz
        configflags:
            - -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
            - -DCMAKE_INSTALL_PREFIX=/usr
            - -DCMAKE_BUILD_TYPE=Debug
        build-packages: [libfam-dev]
        stage-packages: [libfam0]
        filesets:
            exclusion:
                - -usr/lib/*/cmake/*
                - -usr/include/*
                - -usr/share/ECM/*
                - -usr/share/doc/*
                - -usr/share/man/*
        snap: [$exclusion]
